Lucky-Draw:
  sqlHost: 127.0.0.1
  host: 192.168.198.128
  mysql-port: 3306
  nacos-port: 8848
  redis-port: 6379
  druid-password: sunwenhao1630
  mq-host1: 192.168.198.128
  mq-port1: 9876
nacos:
  namespace: nacos

DB_HOST: ${Lucky-Draw.sqlHost}:${Lucky-Draw.mysql-port}
DB_NAME: bld
DB_USERNAME: root
DB_PASSWORD: 1234
REDIS_PASSWORD: '000415'


MQ_NAME_SERVER: ${Lucky-Draw.mq-host1}:${Lucky-Draw.mq-port1}
MQ_GROUP: Lucky_Draw



spring:
  mail:
    host: smtp.qq.com
    username: 2196728181@qq.com
    password: uwavkcopjgsyecfe
    properties:
     mail:
        debug=true:
        stmp:socketFactory:class: javax.net.ssl.SSLSocketFactory

register:
  interface: http://127.0.0.1:5173/verify?code=